mpackage = [[MuddlerReload]]
author = [[FieryDev]]
title = [[Muddler hot-reload for FierymudRs]]
description = [[Watches the repo's .output file (UNC to WSL2 path) and reinstalls FierymudRs.mpackage when Muddler rebuilds it. Hot-reload for in-Mudlet iteration.]]
version = [[0.9.0]]
created = [[2026-05-11]]
